spring.application.name=nameserver

server.port=8761

# Eureka server should not self-register
eureka.client.register-with-eureka=false

# Eureka server should not fetch registry
eureka.client.fetch-registry=false

# Prefer IP address when registering instances
eureka.instance.prefer-ip-address=true










